# TensorFlow

In [3]:
import tensorflow as tf

In [24]:
#공부 시간
x_data = [2, 4, 6, 8]
#점수
y_data = [ 81, 93, 91, 97]

In [25]:
tf.reset_default_graph()
sess =  tf.Session()
#독립 변수와 종속 변수의 미리 저장하는 공간
X = tf.placeholder(tf.float32, shape=None)
Y = tf.placeholder(tf.float32, shape=None)
#가중치 설정
W = tf.Variable(tf.random_normal([1], name='weight'))
#편향
b = tf.Variable(tf.random_normal([1], name='bias'))

In [26]:
#가설 설정 -> 함수를 입력
hypo = W*X + b
#손실 함수
cost = tf.reduce_mean(tf.square(hypo-Y))
#손실 함수 최소와 방법
opti = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = opti.minimize(cost)
print(train)

name: "GradientDescent"
op: "NoOp"
input: "^GradientDescent/update_Variable/ApplyGradientDescent"
input: "^GradientDescent/update_Variable_1/ApplyGradientDescent"



In [37]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(4001):
        cost_val, W_val, b_val, train_val = sess.run([cost,W,b,train], feed_dict={X: x_data, Y: y_data})
        if step % 40 == 0:
            print(step, "손실 : " , cost_val, "\t가중치 : ", W_val, "\t편향 : ", b_val)
    print("H(4) 예측 : ", sess.run(hypo, feed_dict={X: [8]}))

0 손실 :  7370.097 	가중치 :  [9.423726] 	편향 :  [3.0380838]
40 손실 :  737.03064 	가중치 :  [13.343806] 	편향 :  [13.095284]
80 손실 :  570.2772 	가중치 :  [11.998278] 	편향 :  [21.124825]
120 손실 :  441.68164 	가중치 :  [10.816684] 	편향 :  [28.176075]
160 손실 :  342.51205 	가중치 :  [9.779049] 	편향 :  [34.368237]
200 손실 :  266.0351 	가중치 :  [8.867833] 	편향 :  [39.80598]
240 손실 :  207.05836 	가중치 :  [8.067637] 	편향 :  [44.581207]
280 손실 :  161.57703 	가중치 :  [7.364933] 	편향 :  [48.774643]
320 손실 :  126.50299 	가중치 :  [6.7478433] 	편향 :  [52.457172]
360 손실 :  99.455025 	가중치 :  [6.2059393] 	편향 :  [55.691025]
400 손실 :  78.59625 	가중치 :  [5.730057] 	편향 :  [58.530888]
440 손실 :  62.510525 	가중치 :  [5.3121533] 	편향 :  [61.024757]
480 손실 :  50.105686 	가중치 :  [4.945166] 	편향 :  [63.21478]
520 손실 :  40.53936 	가중치 :  [4.62289] 	편향 :  [65.137985]
560 손실 :  33.16206 	가중치 :  [4.339877] 	편향 :  [66.82689]
600 손실 :  27.472971 	가중치 :  [4.091348] 	편향 :  [68.31]
640 손실 :  23.085634 	가중치 :  [3.8730946] 	편향 :  [69.61244]
680 손실 :  19.702248 	가중치 :

In [117]:
tf.reset_default_graph()

x1_data = [73, 93, 89, 96, 73]
x2_data = [80, 88, 91, 98, 66]
x3_data = [75, 93, 90, 100, 70]
y_data = [72, 88, 92, 100, 71]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random.normal([1]), name='weight1')
w2 = tf.Variable(tf.random.normal([1]), name='weight2')
w3 = tf.Variable(tf.random.normal([1]), name='weight3')

b = tf.Variable(tf.random.normal([1]), name='bias')

In [123]:
hypo = x1*w1 + x2 * w2 +x3 * w3 + b
cost = tf.reduce_mean(tf.square(hypo - Y))
opti = tf.train.GradientDescentOptimizer(learning_rate=0.00001)
train = opti.minimize(cost)

In [125]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        cost_val, hypo_val, _ = sess.run([cost, hypo, train], feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
        
        if step % 10 == 0:
            print(step, "손실: ", cost_val, "\t예측: ", hypo_val)

0 손실:  43434.57 	예측:  [-110.43775 -130.35664 -129.63376 -141.55359  -98.52884]
10 손실:  7.953353 	예측:  [73.91049  91.212944 88.68421  96.18942  70.47196 ]
20 손실:  7.5542235 	예측:  [74.46995  91.882126 89.34523  96.90946  70.98139 ]
30 손실:  7.552661 	예측:  [74.47333  91.88296  89.347694 96.91236  70.98104 ]
40 손실:  7.5511003 	예측:  [74.47502  91.881775 89.34817  96.9131   70.97915 ]
50 손실:  7.549539 	예측:  [74.47671  91.88058  89.34863  96.913826 70.97726 ]
60 손실:  7.547988 	예측:  [74.478386 91.879395 89.349106 96.91455  70.97537 ]
70 손실:  7.546449 	예측:  [74.480064 91.87821  89.34957  96.915276 70.973495]
80 손실:  7.544912 	예측:  [74.48173 91.87702 89.35002 96.91599 70.97162]
90 손실:  7.543396 	예측:  [74.48338  91.87585  89.35048  96.9167   70.969734]
100 손실:  7.541865 	예측:  [74.48504  91.87467  89.35094  96.91743  70.967865]
110 손실:  7.540347 	예측:  [74.48669  91.8735   89.351395 96.91814  70.966   ]
120 손실:  7.538827 	예측:  [74.488335 91.87233  89.35185  96.91886  70.96414 ]
130 손실:  7.5373297 	예

1090 손실:  7.4190164 	예측:  [74.626755 91.77369  89.389534 96.98316  70.80336 ]
1100 손실:  7.41802 	예측:  [74.62798  91.77281  89.389854 96.98378  70.80189 ]
1110 손실:  7.417025 	예측:  [74.6292   91.771935 89.39018  96.98438  70.80042 ]
1120 손실:  7.416028 	예측:  [74.63042  91.771065 89.3905   96.985    70.79895 ]
1130 손실:  7.4150314 	예측:  [74.63163  91.770195 89.39083  96.98561  70.79749 ]
1140 손실:  7.414037 	예측:  [74.63285  91.769325 89.39116  96.98623  70.796036]
1150 손실:  7.413045 	예측:  [74.634056 91.768456 89.39148  96.98684  70.79458 ]
1160 손실:  7.412075 	예측:  [74.63526 91.76759 89.3918  96.98744 70.79313]
1170 손실:  7.4110885 	예측:  [74.63646 91.76673 89.39212 96.98805 70.79168]
1180 손실:  7.4101324 	예측:  [74.63766  91.76588  89.39243  96.988655 70.79024 ]
1190 손실:  7.4091654 	예측:  [74.638855 91.76503  89.39276  96.989265 70.7888  ]
1200 손실:  7.408188 	예측:  [74.64004  91.764175 89.393074 96.989876 70.78736 ]
1210 손실:  7.4072227 	예측:  [74.64122  91.76332  89.393394 96.99047  70.78593 ]
1220

In [130]:
x_data = [ [73, 80, 75], [93, 88, 93], [89, 91, 90], [96, 98, 100], [73, 66, 70] ] 
y_data = [ [72], [88], [92], [100], [71] ]
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random.normal([3,1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')

# 행렬의 곱으로 가설을 설정한다.
hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.00001) 
train = optimizer.minimize(cost)
with tf.Session( ) as sess:
    sess.run(tf.global_variables_initializer( )) 
    for step in range(2001):
        cost_val, hy_val, _ = sess.run( [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data} )
        if step % 10 == 0:
            print(step, "\n손실: ", cost_val, "\n예측:\n", hy_val)

0 
손실:  61142.363 
예측:
 [[-141.95125]
 [-173.81699]
 [-169.481  ]
 [-185.51448]
 [-132.7099 ]]
10 
손실:  10.378398 
예측:
 [[76.76391 ]
 [89.074005]
 [89.54387 ]
 [96.55824 ]
 [67.811676]]
20 
손실:  9.805435 
예측:
 [[77.41948 ]
 [89.87362 ]
 [90.32564 ]
 [97.41072 ]
 [68.423546]]
30 
손실:  9.792234 
예측:
 [[77.4153  ]
 [89.880226]
 [90.32606 ]
 [97.4123  ]
 [68.43053 ]]
40 
손실:  9.779059 
예측:
 [[77.40913]
 [89.88442]
 [90.32411]
 [97.41132]
 [68.43568]]
50 
손실:  9.765962 
예측:
 [[77.40298 ]
 [89.8886  ]
 [90.32218 ]
 [97.410355]
 [68.4408  ]]
60 
손실:  9.752951 
예측:
 [[77.39684 ]
 [89.89277 ]
 [90.32025 ]
 [97.40937 ]
 [68.445915]]
70 
손실:  9.739989 
예측:
 [[77.39072]
 [89.89693]
 [90.31831]
 [97.4084 ]
 [68.45101]]
80 
손실:  9.727098 
예측:
 [[77.384605]
 [89.90107 ]
 [90.31639 ]
 [97.407425]
 [68.45609 ]]
90 
손실:  9.714266 
예측:
 [[77.37851 ]
 [89.90519 ]
 [90.314476]
 [97.406456]
 [68.46115 ]]
100 
손실:  9.701532 
예측:
 [[77.372444]
 [89.909325]
 [90.31255 ]
 [97.405495]
 [68.46622 ]]
110 
손실:  9.6

1360 
손실:  8.52841 
예측:
 [[76.72142 ]
 [90.35031 ]
 [90.10638 ]
 [97.3087  ]
 [69.000656]]
1370 
손실:  8.521848 
예측:
 [[76.71707 ]
 [90.353264]
 [90.104996]
 [97.30811 ]
 [69.00417 ]]
1380 
손실:  8.515285 
예측:
 [[76.712715]
 [90.35619 ]
 [90.10361 ]
 [97.30752 ]
 [69.00768 ]]
1390 
손실:  8.508783 
예측:
 [[76.70839 ]
 [90.35913 ]
 [90.102234]
 [97.30694 ]
 [69.011185]]
1400 
손실:  8.502302 
예측:
 [[76.70406]
 [90.36204]
 [90.10085]
 [97.30634]
 [69.01467]]
1410 
손실:  8.495878 
예측:
 [[76.69975 ]
 [90.36495 ]
 [90.09947 ]
 [97.305756]
 [69.01814 ]]
1420 
손실:  8.489468 
예측:
 [[76.69546 ]
 [90.367874]
 [90.098114]
 [97.30518 ]
 [69.02162 ]]
1430 
손실:  8.483099 
예측:
 [[76.69117 ]
 [90.370766]
 [90.09675 ]
 [97.304596]
 [69.02508 ]]
1440 
손실:  8.47677 
예측:
 [[76.68689 ]
 [90.373665]
 [90.095375]
 [97.304016]
 [69.02853 ]]
1450 
손실:  8.470452 
예측:
 [[76.68262]
 [90.37654]
 [90.09402]
 [97.30344]
 [69.03196]]
1460 
손실:  8.464178 
예측:
 [[76.67837 ]
 [90.379425]
 [90.09267 ]
 [97.30287 ]
 [69.03539 ]]


In [39]:
df = pd.read_excel('/Users/lesson6_mac/Downloads/TeamProject/trial2/all.xlsx')
df.head()

temp  wind  rain  humi   dew  snow  accident
0 -5.35  1.50  0.00  70.0 -9.85   0.0         0
1 -5.75  1.35  0.00  71.5 -9.85   0.0         0
2 -2.95  1.50  0.00  69.5 -6.15   0.0         0
3 -0.25  2.30  0.25  70.5 -3.45   0.0         0
4  0.80  3.90  0.00  69.5 -2.25   0.0         0

In [61]:
#temp를 변수값
x_data = list(df['temp'])
#accident를 종속변수값
y_data = list(df['dew'])

In [62]:
tf.reset_default_graph()
sess =  tf.Session()
#독립 변수와 종속 변수의 미리 저장하는 공간
X = tf.placeholder(tf.float32, shape=None)
Y = tf.placeholder(tf.float32, shape=None)
#가중치 설정
W = tf.Variable(tf.random_normal([1], name='weight'))
#편향
b = tf.Variable(tf.random_normal([1], name='bias'))

In [74]:
#가설 설정 -> 함수를 입력
hypo = W*X + b
#손실 함수
cost = tf.reduce_mean(tf.square(hypo-Y))
#손실 함수 최소와 방법
opti = tf.train.GradientDescentOptimizer(learning_rate=0.001)
train = opti.minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, b_val, train_val = sess.run([cost,W,b,train], feed_dict={X: x_data, Y: y_data})
        if step % 20 == 0:
            print(step, "손실 : " , cost_val, "\t가중치 : ", W_val, "\t편향 : ", b_val)
    print("H(x_data) 예측 : ", sess.run(hypo, feed_dict={X: x_data[0:5]}))

0 손실 :  110.725204 	가중치 :  [0.93182737] 	편향 :  [0.7293799]
20 손실 :  49.84726 	가중치 :  [0.6933097] 	편향 :  [0.5943321]
40 손실 :  49.10973 	가중치 :  [0.69912016] 	편향 :  [0.4730899]
60 손실 :  48.396854 	가중치 :  [0.7048324] 	편향 :  [0.3539034]
80 손실 :  47.707985 	가중치 :  [0.71044767] 	편향 :  [0.23673771]
100 손실 :  47.042343 	가중치 :  [0.71596783] 	편향 :  [0.12155858]
120 손실 :  46.398933 	가중치 :  [0.72139436] 	편향 :  [0.00833224]
140 손실 :  45.777355 	가중치 :  [0.72672886] 	편향 :  [-0.10297437]
160 손실 :  45.176537 	가중치 :  [0.73197293] 	편향 :  [-0.21239379]
180 손실 :  44.595936 	가중치 :  [0.73712814] 	편향 :  [-0.31995806]
200 손실 :  44.03484 	가중치 :  [0.7421959] 	편향 :  [-0.42569864]
H(x_data) 예측 :  [-4.3964467 -4.693325  -2.6151767 -0.6112476  0.1680581]
